# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.kernel.sysctl = {
    "net.ipv4.tcp_mtu_probing" = 1;
  };
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "none";
      fsType = "tmpfs";
      options = [ "mode=0755" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/AD18-7C44";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/nix" =
    {
      device = "/dev/disk/by-uuid/f3aa695b-9f31-4673-bc6f-04110984ba54";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/etc" =
    {
      device = "/dev/disk/by-uuid/f3aa695b-9f31-4673-bc6f-04110984ba54";
      fsType = "btrfs";
      options = [ "subvol=etc" ];
    };

  fileSystems."/var/log" =
    {
      device = "/dev/disk/by-uuid/f3aa695b-9f31-4673-bc6f-04110984ba54";
      fsType = "btrfs";
      options = [ "subvol=log" ];
    };

  fileSystems."/root" =
    {
      device = "/dev/disk/by-uuid/f3aa695b-9f31-4673-bc6f-04110984ba54";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/f3aa695b-9f31-4673-bc6f-04110984ba54";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/9895dfaa-1635-499b-8cd9-20605da2b79a"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp7s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
